/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNav: typeof import('./components/AppNav.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PlayerCard: typeof import('./components/PlayerCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsRadarChart: typeof import('./components/StatsRadarChart.vue')['default']
  }
}
