/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/Game/[GameID]': RouteRecordInfo<'/Game/[GameID]', '/Game/:GameID', { GameID: ParamValue<true> }, { GameID: ParamValue<false> }, '/Game/[GameID]/EndState' | '/Game/[GameID]/IdentitySelection' | '/Game/[GameID]/Lobby' | '/Game/[GameID]/MissionPhase' | '/Game/[GameID]/SuspicionPhase' | '/Game/[GameID]/TeamSelection' | '/Game/[GameID]/TeamVote'>,
    '/Game/[GameID]/EndState': RouteRecordInfo<'/Game/[GameID]/EndState', '/Game/:GameID/EndState', { GameID: ParamValue<true> }, { GameID: ParamValue<false> }>,
    '/Game/[GameID]/IdentitySelection': RouteRecordInfo<'/Game/[GameID]/IdentitySelection', '/Game/:GameID/IdentitySelection', { GameID: ParamValue<true> }, { GameID: ParamValue<false> }>,
    '/Game/[GameID]/Lobby': RouteRecordInfo<'/Game/[GameID]/Lobby', '/Game/:GameID/Lobby', { GameID: ParamValue<true> }, { GameID: ParamValue<false> }>,
    '/Game/[GameID]/MissionPhase': RouteRecordInfo<'/Game/[GameID]/MissionPhase', '/Game/:GameID/MissionPhase', { GameID: ParamValue<true> }, { GameID: ParamValue<false> }>,
    '/Game/[GameID]/SuspicionPhase': RouteRecordInfo<'/Game/[GameID]/SuspicionPhase', '/Game/:GameID/SuspicionPhase', { GameID: ParamValue<true> }, { GameID: ParamValue<false> }>,
    '/Game/[GameID]/TeamSelection': RouteRecordInfo<'/Game/[GameID]/TeamSelection', '/Game/:GameID/TeamSelection', { GameID: ParamValue<true> }, { GameID: ParamValue<false> }>,
    '/Game/[GameID]/TeamVote': RouteRecordInfo<'/Game/[GameID]/TeamVote', '/Game/:GameID/TeamVote', { GameID: ParamValue<true> }, { GameID: ParamValue<false> }>,
    '/Leaderboard': RouteRecordInfo<'/Leaderboard', '/Leaderboard', Record<never, never>, Record<never, never>>,
    '/Login/Login': RouteRecordInfo<'/Login/Login', '/Login/Login', Record<never, never>, Record<never, never>>,
    '/Login/UserNameSignup': RouteRecordInfo<'/Login/UserNameSignup', '/Login/UserNameSignup', Record<never, never>, Record<never, never>>,
    '/Profile/[Username]': RouteRecordInfo<'/Profile/[Username]', '/Profile/:Username', { Username: ParamValue<true> }, { Username: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/About.vue': {
      routes: '/About'
      views: never
    }
    'src/pages/Game/[GameID].vue': {
      routes: '/Game/[GameID]' | '/Game/[GameID]/EndState' | '/Game/[GameID]/IdentitySelection' | '/Game/[GameID]/Lobby' | '/Game/[GameID]/MissionPhase' | '/Game/[GameID]/SuspicionPhase' | '/Game/[GameID]/TeamSelection' | '/Game/[GameID]/TeamVote'
      views: 'default'
    }
    'src/pages/Game/[GameID]/EndState.vue': {
      routes: '/Game/[GameID]/EndState'
      views: never
    }
    'src/pages/Game/[GameID]/IdentitySelection.vue': {
      routes: '/Game/[GameID]/IdentitySelection'
      views: never
    }
    'src/pages/Game/[GameID]/Lobby.vue': {
      routes: '/Game/[GameID]/Lobby'
      views: never
    }
    'src/pages/Game/[GameID]/MissionPhase.vue': {
      routes: '/Game/[GameID]/MissionPhase'
      views: never
    }
    'src/pages/Game/[GameID]/SuspicionPhase.vue': {
      routes: '/Game/[GameID]/SuspicionPhase'
      views: never
    }
    'src/pages/Game/[GameID]/TeamSelection.vue': {
      routes: '/Game/[GameID]/TeamSelection'
      views: never
    }
    'src/pages/Game/[GameID]/TeamVote.vue': {
      routes: '/Game/[GameID]/TeamVote'
      views: never
    }
    'src/pages/Leaderboard.vue': {
      routes: '/Leaderboard'
      views: never
    }
    'src/pages/Login/Login.vue': {
      routes: '/Login/Login'
      views: never
    }
    'src/pages/Login/UserNameSignup.vue': {
      routes: '/Login/UserNameSignup'
      views: never
    }
    'src/pages/Profile/[Username].vue': {
      routes: '/Profile/[Username]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
